# DO NOT CHANGE !!!
config-version: 4

# The name of the Enchantment
name: Replenish

# The rarity of the enchantment
# Probably useless, I don't even know, what this does...
# choose out of this list:
# COMMON, UNCOMMON, RARE, VERY_RARE
rarity: UNCOMMON

application:
  # Whether it should be possible to apply the enchantment on the anvil (recommended)
  anvil: true

  # Whether it should be possible to apply the enchantment via drag & drop in the inventory (optional)
  # Only works in survival mode
  inventory: true

  # The levels it costs to apply the enchantment via drag & drop in the inventory (set to 0 to make the application via drag & drop in the inventory free)
  inventory-level-cost: 2

level-multiplier:
  # The following multipliers times the final level of the enchantment gives the level cost of this enchantment while combining two items on the anvil
  # The "book" value is used when the right item is an enchantment book, the "item" value otherwise
  item: 1
  book: 1

external-enchantment-level-multiplier:
  # Add the level multipliers for custom enchantments from other plugins here,
  # as this plugin completely overwrites the anvil and the level costs for unknown enchantments defaults to 0
  # Format:
  # key: (you will get a message "Could not identify Enchantment "{key}"! Setting level cost to 0..." whenever this plugin detects an unknown enchantment,
  #       {key} will be replaced with the actual key)
  #   item: {item-multiplier}
  #   book: {book-multiplier}
  example_key:
    item: 6
    book: 3

crops:
  # A list of all crops you want to be affected by the replenish-enchantment
  # Currently supported:
  # - "WHEAT", "CARROTS", "POTATOES", "BEETROOTS" and "NETHER_WART"
  - "WHEAT"
  - "CARROTS"
  - "POTATOES"
  - "BEETROOTS"
  - "NETHER_WART"

################################
#         Permissions          #
################################

# The permission for the /r-getbook command
# Set to "" to disable the permission (Players need to be OP then)
permission-get-book: re.cmd.get.book

# The permission for the /r-givebook command
# Set to "" to disable the permission (Players need to be OP then)
permission-give-book: re.cmd.give.book

permission-get-hoe:
  # The permission for the wooden hoe with the /r-gethoe command
  # Set to "" to disable the permission (Players need to be OP then)
  wood: re.cmd.get.hoe.wood

  # The permission for the stone hoe with the /r-gethoe command
  # Set to "" to disable the permission (Players need to be OP then)
  stone: re.cmd.get.hoe.stone

  # The permission for the golden hoe with the /r-gethoe command
  # Set to "" to disable the permission (Players need to be OP then)
  gold: re.cmd.get.hoe.gold

  # The permission for the iron hoe with the /r-gethoe command
  # Set to "" to disable the permission (Players need to be OP then)
  iron: re.cmd.get.hoe.iron

  # The permission for the diamond hoe with the /r-gethoe command
  # Set to "" to disable the permission (Players need to be OP then)
  diamond: re.cmd.get.hoe.diamond

  # The permission for the netherite hoe with the /r-gethoe command
  # Set to "" to disable the permission (Players need to be OP then)
  netherite: re.cmd.get.hoe.netherite

  # The permission for the full-enchanted hoe option with the /r-gethoe command
  # Set to "" to disable the permission (Players need to be OP then)
  full-enchanted: re.cmd.get.hoe.full-enchanted

permission-give-hoe:
  # The permission for the wooden hoe with the /r-givehoe command
  # Set to "" to disable the permission (Players need to be OP then)
  wood: re.cmd.give.hoe.wood

  # The permission for the stone hoe with the /r-givehoe command
  # Set to "" to disable the permission (Players need to be OP then)
  stone: re.cmd.give.hoe.stone

  # The permission for the golden hoe with the /r-givehoe command
  # Set to "" to disable the permission (Players need to be OP then)
  gold: re.cmd.give.hoe.gold

  # The permission for the iron hoe with the /r-givehoe command
  # Set to "" to disable the permission (Players need to be OP then)
  iron: re.cmd.give.hoe.iron

  # The permission for the diamond hoe with the /r-givehoe command
  # Set to "" to disable the permission (Players need to be OP then)
  diamond: re.cmd.give.hoe.diamond

  # The permission for the netherite hoe with the /r-givehoe command
  # Set to "" to disable the permission (Players need to be OP then)
  netherite: re.cmd.give.hoe.netherite

  # The permission for the full-enchanted hoe option with the /r-givehoe command
  # Set to "" to disable the permission (Players need to be OP then)
  full-enchanted: re.cmd.give.hoe.full-enchanted
