# DO NOT CHANGE !!!
config-version: 1

# The name of the Enchantment
name: Replenish

# The rarity of the enchantment
# Probably useless, I don't even know, what this does...
# choose out of this list:
# COMMON, UNCOMMON, RARE, VERY_RARE
rarity: UNCOMMON