name: ReplenishEnchantment
version: '${project.version}'
main: de.drachir000.survival.replenishenchantment.ReplenishEnchantment
api-version: 1.18
authors: [ Drachir000 ]
description: This plugin adds an enchantment for hoes that automatically replants seeds when harvesting, making farming more efficient
website: https://github.com/Drachir000/ReplenishEnchantment
commands:
  replenish-getbook:
    description: gives you the Enchantment-Book
    usage: /replenish-getbook
    aliases: [r-getbook]
  replenish-givebook:
    description: gives a player the Enchantment-Book
    usage: /replenish-givebook <Player>
    aliases: [r-givebook]
  replenish-gethoe:
    description: gives you a Enchanted Hoe
    usage: /replenish-gethoe [<Material(WOOD/IRON/etc.)>] [<full-enchanted(true/false)>]
    aliases: [r-gethoe]
  replenish-givehoe:
    description: gives you a Enchanted Hoe
    usage: /replenish-givehoe <Player> <Material(WOOD/IRON/etc.)> [<full-enchanted(true/false)>]
    aliases: [r-givehoe]