name: ReplenishEnchantment
version: '${project.version}'
main: de.drachir000.survival.replenishenchantment.ReplenishEnchantment
api-version: 1.19
authors: [ Drachir000 ]
description: Adds a Replenish Enchantment to the game, which automatically replants seeds while farming
website: https://drachir000.de
commands:
  replenish-getbook:
    description: gives you the Enchantment-Book
    usage: /replenish-getbook
    aliases: [r-getbook]
  replenish-givebook:
    description: gives a player the Enchantment-Book
    usage: /replenish-givebook <Player>
    aliases: [r-givebook]
  replenish-gethoe:
    description: gives you a Enchanted Hoe
    usage: /replenish-gethoe [<Material(WOOD/IRON/etc.)>] [<full-enchanted(true/false)>]
    aliases: [r-gethoe]
  replenish-givehoe:
    description: gives you a Enchanted Hoe
    usage: /replenish-givehoe <Player> <Material(WOOD/IRON/etc.)> [<full-enchanted(true/false)>]
    aliases: [r-givehoe]