name: ReplenishEnchantment
version: '${project.version}'
main: de.drachir000.survival.replenishenchantment.ReplenishEnchantment
api-version: 1.17
authors: [ Drachir000 ]
description: This plugin adds an enchantment for hoes that automatically replants seeds when harvesting, making farming more efficient
website: https://github.com/Drachir000/ReplenishEnchantment
commands:
  replenish-get:
    description: gives you the Enchantment-Book, an enchanted hoe or axe
    usage: /replenish-get <BOOK/HOE/AXE> [<Material(WOOD/IRON/etc.)>] [<full-enchanted(true/false)>]
    aliases: [r-get]
  replenish-give:
    description: gives a player the Enchantment-Book, an enchanted hoe or axe
    usage: /replenish-give <BOOK/HOE/AXE> <Player> [<Material(WOOD/IRON/etc.)>] [<full-enchanted(true/false)>]
    aliases: [r-give]